- name: creating webimage and creating container
  hosts: webservers
  tasks:
  - name: build image
    docker_image:
      path: /home/ubuntu
      name: webimages
  - name: web container
    docker_container:
      name: web1
      image: webimages
      state: started
      ports:
      - "8060:80"
      tty: true
      detach: true
